### PR TITLE
Upgrade nextjs and chakra-ui version

### PR DESCRIPTION
**Pull request by indraarianggi**
Found [your tweet on twitter](https://twitter.com/F2aldi/status/1579351179447832576), so I wanted to contribute to this repository as part of the hacktoberfest2022 event.

- [x] upgrade nextjs version to 12.3.1
- [x] upgrade chakra-ui version to 2.3.5
- [x] also upgrade the version of related dependencies.

### CODE REVIEW

**Comment by naufaldi** [comment]
sorry for late review. Here error in build NextJS.
Can you solve it? and try to build in local first before create PR.

Thanks 
Screen Shot 2022-10-13 at 18 18 07

**Comment by naufaldi** [comment]
@indraarianggi any update?

**Comment by indraarianggi** [comment]
Sorry, I just saw your reply

Build local success
Screen Shot 2022-10-19 at 08 21 09

**Comment by indraarianggi** [comment]
Just fixed the error based on screenshot you provided. I don't know why in local it doesn't show up.

This is what I did:
- Upgrade framer-motion version to 4.0.0 (according to required peer dependencies for chakra-ui is >=4.0.0)
- Fix implementation of framer-motion in Header and Footer components (reference: [Chakra UI + Framer Motion](https://chakra-ui.com/getting-started/with-framer#as-prop))

Please review it again @naufaldi . Thanks :)

**Comment by indraarianggi** [comment]
any updates @naufaldi ?

**Pull request merged**
